# Generated by Django 4.1.3 on 2022-11-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=70)),
                ('prod_number', models.BigIntegerField()),
                ('prod_details', models.CharField(max_length=400)),
                ('prod_price', models.BigIntegerField()),
                ('prod_stock', models.BigIntegerField()),
                ('prod_image', models.ImageField(upload_to='product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
        ),
    ]
