# Generated by Django 4.1.3 on 2022-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_firstname', models.CharField(default='', max_length=20)),
                ('c_secondname', models.CharField(max_length=20)),
                ('c_email', models.CharField(max_length=70)),
                ('c_phone', models.BigIntegerField()),
                ('c_Address', models.CharField(max_length=300)),
                ('c_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=70)),
                ('s_phone', models.BigIntegerField()),
                ('s_Address', models.CharField(max_length=300)),
                ('s_accnumber', models.BigIntegerField()),
                ('s_ifsc', models.CharField(max_length=70)),
                ('s_accholdername', models.CharField(max_length=20)),
                ('s_password', models.CharField(default='', max_length=8)),
                ('s_pic', models.ImageField(default='', upload_to='seller/')),
            ],
        ),
    ]
